package com.apicatalog.tree.io;

/**
 * Exception thrown when a node cannot be read, written, or generated by a
 * {@code NodeReader}, {@code NodeWriter}, or {@code NodeGenerator}.
 * <p>
 * This exception indicates that a node could not be parsed, serialized, or
 * processed due to invalid data, unsupported structure, or adapter failure.
 * </p>
 */
public class TreeException extends Exception {

    private static final long serialVersionUID = -5531531271614115471L;

}
