package com.apicatalog.tree.io;

/**
 * Exception thrown when a node cannot be read, written, or generated by a
 * {@code TreeParser}, {@code TreeRenderer}, or {@code TreeGenerator}.
 * <p>
 * This exception indicates that a node could not be parsed, serialized, or
 * processed due to invalid data, unsupported structure, or adapter failure.
 * </p>
 */
public class TreeIOException extends Exception {

    private static final long serialVersionUID = -8158955344692239114L;

    public TreeIOException(Throwable e) {
        super(e);
    }

    public TreeIOException(String message) {
        super(message);
    }

}
